### PR TITLE
Logos and diversity metadata

### PR DESCRIPTION
**Pull request by JohnKilleen**
@timstallmann Added Durham Compass logos (not City, County or DW, yet) and updated diversity index metadata

### CODE REVIEW

**Comment by timstallmann** [comment]
@JohnKilleen the logos come through great on this branch -- but a reminder that the diversity, metric tables & data.js configs are all in the quality of life data repo, not this one. Also in the commit history you mention some changes to the blue & pink selection colors but I don't see those changes reflected in the comparison either?

**Comment by JohnKilleen** [comment]
@timstallmann . updating and branching for the data repo next, thanks! Also, the return to pink hex reference is for where I made a change in main.css that appeared not to work - just reverted knowing you might be working on the global pink removal...

**Comment by timstallmann** [comment]
Ahh I see! Thx..

**Comment by timstallmann** [comment]
@JohnKilleen in the future you could also do a rebase command and just exclude the pink hex commit entirely, that way there won't be two extra commits (the initial one and the reversion) in the commit history. Keeps things cleaner overall.

**Pull request merged**
